### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Zy3iX** [cludeex/spammer#13]
Сколько вводить количество потоков?
Я вводил 32 и другие значения но за все время пришло только 1 смс сообщение

**Comment by Blinc13** [comment]
Проблемма не в потоках, а в том что у сервисов, которые присылают смс были обновления

**Comment by Limon4ik885** [comment]
And what to do now?

**Comment by Limon4ik885** [comment]
Что делать теперь?

**Comment by Blinc13** [comment]
Искать другой, либо ждать пока этот обновят
